### ISSUE TITLE
Feature request: Allow OCR app to connect to docker container on remote server

### ISSUE THREAD

**Issue by e-alfred** [janis91/ocr#102]
Hello,

it would be good to be able to run the docker container on a separate docker host and connect the OCR app from a Nextcloud instance in a secure way. Many installations are on shared hosting, so a docker installation can't be run on the same system for example.

**Comment by janis91** [comment]
I don't see a problem with a distributed setup like the one you describe here. You can configure your docker worker completely (redis host, redis port, redis db). Moreover you can bind the data and output directory to the docker container like you want to. In Nextcloud you only have to configure the redis endpoint in the admin settings section (It should also work with a host name or IP in a cloud setup). Maybe I don't see the point but I think this is not an issue.

**Comment by e-alfred** [comment]
The problem is that there is no authentication and also no transport security for the Redis server. This would be needed if it is run on a different server, especially on the internet. Here is more about it:

https://redis.io/topics/security

 I think enabling Redis authentication would be a good step to mitigate this as well as instructions on how to set up a reverse proxy doing TLS.

**Comment by janis91** [comment]
Confirmed.

**Comment by janis91** [comment]
@e-alfred do you have any knowledge how to setup such a secure cloud environment? I am not that familiar with securing a docker endpoint. Should the TLS endpoint be in the same container or reside in its own?

**Comment by e-alfred** [comment]
Well, one thing would be to allow setting an auth password as a docker environment variable for the container. In the settings page for the OCR app, a corresponding password field would have to be implemented.

For setting up the redis server in a secure way, this guide could help:

https://www.digitalocean.com/community/tutorials/how-to-secure-your-redis-installation-on-ubuntu-14-04

For secure communication between networked systems here is a guide with the spiped (officially recommended by redis):

https://www.digitalocean.com/community/tutorials/how-to-encrypt-traffic-to-redis-with-spiped-on-ubuntu-16-04

**Comment by janis91** [comment]
The password field has  been added. As far as I am not able (and even not willing) to adjust the nextcloud docker image and adding tls encryption to the redis communication as well as for the OCR worker, I suggest to use the docker swarm ability to have a so called "overlay network" setup and use the encryption feature of it. This should be a good way to have a distributed cloud setup. docker swarm is also widely used and standard docker. Therefore I close this issue. 
I also documented this in the wiki.

Thanks for your answers!
