### ISSUE TITLE
l10n: Make t() string use plural format

### ISSUE THREAD

**Issue by rakekniven** [janis91/ocr#103]
https://github.com/janis91/ocr/blob/master/js/dist/ocrapp.js#L356

No file(s) selected.

Please make this using plural format.

**Comment by janis91** [comment]
I actually think this can be the single format as it is only checking for empty selection array. but the next displayError method has to be changed to the plural format. Thanks!

**Comment by janis91** [comment]
Fixed in #110 
Thanks!
