### ISSUE TITLE
OCr  doesn't scan files

### ISSUE THREAD

**Issue by Happyfeet01** [janis91/ocr#117]
# Bug report / Feature request
## Expected Behavior
When i click on "Schrifterkennung" i get only this Message: 

`  Schrifterkennung gestartet: 1 neue Datei in der Warteschlange.`

after a while i get
`
"Schrifterkennung für 2 Dateien fehlgeschlagen. Für weitere Informationen sieh in deinen Persönlichen Einstellungen nach."
`

* OCR version used: 3.0.0-beta.1
* Browser Name and version: Firefox Dektop also Firefox Android (latest Version)
* Operating System and version (desktop or mobile): (Desktop Linux Mint 13.1) (Android 7.1.2)
* ownCloud/nextcloud version: (see ownCloud admin page or version.php) Nextcloud 12.02
* PHP version PHP 7.1.22
* Database version Mysql mysql  Ver 14.14 Distrib 5.7.19, for Linux (x86_64) using  EditLine wrapper
* Are you using encryption: no

## Log File Content (nextcloud/owncloud.log of the "data"-directory)

```
Error | ocr |   | a minute ago
-- | -- | -- | --
Error | ocr |   | a minute ago
```

Redis-Server log ( i donţ know if these log created while scanning)
```

23164:M 20 Aug 08:09:36.049 * 10000 changes in 60 seconds. Saving...
23164:M 20 Aug 08:09:36.052 * Background saving started by pid 8394
8394:C 20 Aug 08:09:36.238 * DB saved on disk
8394:C 20 Aug 08:09:36.239 * RDB: 5 MB of memory used by copy-on-write
23164:M 20 Aug 08:09:36.253 * Background saving terminated with success
23164:M 20 Aug 08:12:15.414 * 10000 changes in 60 seconds. Saving...
23164:M 20 Aug 08:12:15.418 * Background saving started by pid 8491
8491:C 20 Aug 08:12:15.567 * DB saved on disk
8491:C 20 Aug 08:12:15.568 * RDB: 5 MB of memory used by copy-on-write
23164:M 20 Aug 08:12:15.618 * Background saving terminated with success
```

**Comment by stweil** [comment]
Do you use a newer Linux distribution with `systemd` and do you have directories like `/tmp/systemd-private-*`? Then that might be causing the problem, and you will have to fix your installation (see wiki).

**Comment by Happyfeet01** [comment]
i solved it with the correct docker setup. but now i cant connect to the redis docker 
```
2017-08-20T07:17:14.225Z - warn: Connection closed to redis server.
2017-08-20T07:17:14.878Z - error: ERROR: connect ECONNREFUSED 172.18.0.3:63798.
2017-08-20T07:17:14.879Z - warn: Connection closed to redis server.
2017-08-20T07:17:15.594Z - error: ERROR: connect ECONNREFUSED 172.18.0.3:63798.
2017-08-20T07:17:15.595Z - warn: Connection closed to redis server.
```
but the container running and accept incoming connections. I use this different port because i use at 127.0.0.1:6379 redis for the cloud

**Comment by janis91** [comment]
Did you follow the setup instructions of the wiki?

**Comment by janis91** [comment]
Is this still a valid question or did you manage to run it?

**Comment by Happyfeet01** [comment]
Is still a valid question. I try also the local setup with the redis-server installation. But no connection to the redis server from the app. But nextcloud itself user it still.

**Comment by Happyfeet01** [comment]
I try it again look here https://github.com/janis91/ocr/issues/118

**Comment by janis91** [comment]
I think it's not necessary to have two tickets open for the same thing. The local installation is basically not the preferred method, as it comes with some manual configuration that is not really comfortable and pollutes the server environment in terms of new env variables. The last maybe missing part is documented in  #119. Maybe you look there. I guess your main problems where caused by some weird permissions that are set for the data directory, and the docker user didn't have access to read from your nextcloud data dir.
