### ISSUE TITLE
Links on apps.nextcloud.com don't work

### ISSUE THREAD

**Issue by e-alfred** [janis91/ocr#120]
Hello,

your links on https://apps.nextcloud.com/apps/ocr don't work. They point to https://janis91.github.io/ocr/ which gives a 404 error.

**Comment by janis91** [comment]
Thanks for figuring that out. I think this is a issue on the appstore side. I will link this issue to one I create there.

**Comment by xraMsamohT** [comment]
@janis91 But the link on the project start page here on GitHub points the non-existent GitHub Page too. ;-)

**Comment by janis91** [comment]
You were right ;-)
