### ISSUE TITLE
Custom options for tesseract / ocrmypdf commands

### ISSUE THREAD

**Issue by Peter2121** [janis91/ocr#121]
It would be nice to add a possibility to manage the options of tesseract and ocrmypdf commands.
For example, one could limit CPU usage with `--jobs` option of ocrmypdf, force using a certain renderer with `--pdf-renderer` option of ocrmypdf, or change the default output format (pdfa to pdf) with `--output-type` option of ocrmypdf. There are some useful options for tesseract too.
If these options could be configured from Nextcloud OCR settings - it would be really great.

**Comment by janis91** [comment]
Pretty good idea. I will take it on my list.

**Comment by mathiasconradt** [comment]
A bit related: this option would then hopefully also allow to set multiple default languages without having the user to choose. But I created a separate ticket for that: https://github.com/janis91/ocr/issues/128
