### ISSUE TITLE
Error Building worker docker

### ISSUE THREAD

**Issue by angcar** [janis91/ocr#124]
# Bug report / Feature request
## Steps to Reproduce (for bugs)

1. On my Ubuntu 16.04 Server (on path /var/www/html/nextcloud/apps/ocr/ [redis and worker, respectively])
2. Install Docker CE (https://docs.docker.com/engine/installation/linux/docker-ce/ubuntu/#install-using-the-repository) -> No problems
3. Install the app via apps.nextcloud.com (get the last version, unzip & move it to "/var/www/html/nextcloud/apps/ocr/")
4. Build redis images (in redis directory) with command: 
docker build --build-arg PASSWORD="XXXXXX" -t nextcloud/redis .
No problems in this step
5. Build OCR images (in worker directory) with command:
docker build -t nextcloud/ocr . (cuz i want to install default languages like english or spanish...)
6. Got the error in both files attached
[error.txt](https://github.com/janis91/ocr/files/1355622/error.txt)
[error2.txt](https://github.com/janis91/ocr/files/1355623/error2.txt)

## Your Environment

* OCR version used: 3.1.0-beta.1 - nocturno (Inestable)
* Browser Name and version: Firefox (last)
* Operating System and version (desktop or mobile): Ubuntu Server 16.04 LTS
* ownCloud/nextcloud version: (see ownCloud admin page or version.php) 12.0.2
* PHP version: PHP 7.0.22-0ubuntu0.16.04.1
* Database version: psql (PostgreSQL) 9.6.5
* Are you using encryption: no cuz i cant build the worker docker image

## Log File Content (nextcloud/owncloud.log of the "data"-directory)

No errors shown.

**Comment by angcar** [comment]
I get "www-data" permissions to .../ocr/ folder and subfolders & re-run step 5 and its apparently solved.

**Comment by angcar** [comment]
Activate option in NextCloud server is disabled, how could i solve that?
![activate](https://user-images.githubusercontent.com/25975510/31216627-9333e8c2-a9b4-11e7-9640-3d8c1aee8802.PNG)


## Steps to Reproduce (for bugs)


1. On my Ubuntu 16.04 Server (on path /var/www/html/nextcloud/apps/ocr/ [redis and worker, respectively])
2. Install Docker CE (https://docs.docker.com/engine/installation/linux/docker-ce/ubuntu/#install-using-the-repository) -> No problems
3. Install the app via apps.nextcloud.com (get the last version, unzip & move it to "/var/www/html/nextcloud/apps/ocr/")
4. Build redis images (in redis directory) with command: 
docker build --build-arg PASSWORD="XXXXXX" -t nextcloud/redis .
No problems in this step
5. Build OCR images (in worker directory) with command:
docker build -t nextcloud/ocr . (cuz i want to install default languages like english or spanish...)
6. Run Dockers:
docker network create --driver bridge isolated_ocr
for redis: docker run --name redis --network=isolated_ocr -p 6379:6379 -d nextcloud/redis
for ocr: docker run --name ocr --network=isolated_ocr -e "NODE_ENV=production" -e "REDIS_HOST=redis" -e "REDIS_PORT=6379" -e "REDIS_DB=0" -v /var/www/html/nextcloud/data:/home/node/data:ro -v /tmp/nextcloudtemp:/home/node/output -d nextcloud/ocr
7. Added 'tempdirectory' => '/tmp/nextcloudtemp', line to config.php
8. Enable App in our NextCloud Server -> Failed, i cant enable it (attached image)

**Comment by janis91** [comment]
do you have php-redis available (installed as php module)? Just a guess.
