### ISSUE TITLE
[Feature Request] image to pdf

### ISSUE THREAD

**Issue by caiofacchinato** [janis91/ocr#125]
Hey guys,
This plugin works fine with pdf files, but this show a txt file when i have an image file.

I change **'.txt'** to **'.pdf'** in _lib\Service\FileService.php_ and _JobService.php_ and change line (49) in _ocr-processing.services.js_:

>             commandArgs.push(`-l`, `${job.languages.join('+')}`, 'pdf');

It's works, but not like ocrmypdf works in this plugin. You can help me or think about change this in the plugin?

Thank you!

**Comment by janis91** [comment]
Hi, this will not happen i guess and the line you supposed to be changed will also not do this. The programs this app uses are ocrmypdf and tesseract-ocr. one for pdf-to-pdf ocr and the other for image-to-txt ocr. If there isn't a input pdf file, how should one create one as output? As long as these programs can't do the magic, I cannot either. And only to change the file extension doesn't make a real text file a pdf. It's like having an adpater for a garden hose to hdmi. You can put the electrtic signals on the hose, but it will not be converted to water by magic. It will still be electric signals. A text file stays a text file as long as you do not convert it somehow to a pdf which depends on more than changing its name.
I hope this makes it clearer.

**Comment by caiofacchinato** [comment]
Hi, maybe i not clear. But tesseract can do image-to-pdf too, i will explain how this works:
By default, tesseract export image to text, but if you insert 'pdf' after all, its produce a PDF. 
How process show on htop:
![image](https://user-images.githubusercontent.com/22156666/31354458-df09e96c-ad0c-11e7-9efc-678eac9320b7.png)
And yes, this works:
![image](https://user-images.githubusercontent.com/22156666/31355693-b609eb5c-ad11-11e7-907f-b86287edacee.png)
And yes, is a valid PDF file, but the result of OCR is not the same of OCRMYPDF, the text layer is down of expected:
![image](https://user-images.githubusercontent.com/22156666/31355778-f7f7cdd6-ad11-11e7-991f-c050ec57e3a9.png)

Thank you.

**Comment by janis91** [comment]
Oh, I didn't notice that tesseract introduced this capability. I have to apologise then. Then I think this is a feature request. something like a configuration option in the settings. 'Output format for images': txt or pdf.
I will consider this in the next working session for the app.

**Comment by mathiasconradt** [comment]
+1 Looking for exactly the same. Would be nice to have this option, which would be my default.

**Comment by janis91** [comment]
@mathiasconradt I looked at the tesseract feature and reconsidered the aim of this project and I am completely with you. I will make the pdf the default, even more. the txt version will be dropped completely.

**Comment by janis91** [comment]
release 3.2.0 is published and should contian necessary changes :-)
