### ISSUE TITLE
OCR: 1 Datei in der Warteschlange.

### ISSUE THREAD

**Issue by gituser10173** [janis91/ocr#129]
# Bug report 
## Expected Behavior

Dear Janis,
I wan't that after use the function "Texterkennung" inside the nextcloud web page, that after processing i have a OCR-PDF in the same directory the original file is (JPG or PDF).

## Current Behavior

Dear Janis,
after trying your app i have some trouble to use this in the right way. I think that i made something wrong. Now after the second day of raeding and trying - i would like to ask you it you have an ideam what I can do.

Docker + Redis - I have no experience with that two things but I'm interresting in.
For Redis i have read some (like wikipedia and also the admin manual from nextcloud).

For Docker i have read on docker the "beginners" manusl and now understand better (but i think not deep enough).

But i would like to give me a chance to use your OCR App inside my nextcloud. I would take there invoices inside the nextcloud (only private stuff). The source for the invoices are sometimes my scanner.

Many thanks and best regards,

And now the description:

Inside the nextcloud web page i use the function "Texterkennung".
After this a job info is pendig on top on nextcloud web access.

The LOG from nextcloud has the following new lines:
Debug | no app in context | Retrieved the following array from Redis: [] | 2017-12-22T16:16:48+0100
-- | -- | -- | --
Debug | no app in context | Following jobs failed: [] | 2017-12-22T16:16:43+0100
Debug | no app in context | Check if files were processed by ocr and if so, put them to the right dirs. | 2017-12-22T16:16:43+0100

## Possible Solution

It is possible that the running docker containers do not grab the files they should process?

## Steps to Reproduce (for bugs)

1. nextclod 12.04 installation (manual) on LUBUNTU 16.04.03
apt-get install apache2 mariadb-server libapache2-mod-php7.0
apt-get install php7.0-gd php7.0-json php7.0-mysql php7.0-curl php7.0-mbstring
apt-get install php7.0-intl php7.0-mcrypt php-imagick php7.0-xml php7.0-zip
apt-get install php-redis
mariadb without unix socket authentication and admin user "pcadmin"

no ssl hardening (Without -Enabling SSL-) for apache as described in manual - only for inside using (now)

/var/www/nextcloud/config/config.php

<?php
$CONFIG = array (
  'instanceid' => 'ocev1lqkpk9c',
  'passwordsalt' => '1234...',
  'secret' => '1234...',
  'trusted_domains' =>
  array (
    0 => 'nextcloud.trupletz.local',
  ),
  'datadirectory' => '/var/www/nextcloud/data',
  'overwrite.cli.url' => 'http://nextcloud.trupletz.local/nextcloud',
  'dbtype' => 'mysql',
  'version' => '12.0.4.3',
  'dbname' => 'nextcloud',
  'dbhost' => 'localhost:5432',
  'dbport' => '',
  'dbtableprefix' => 'oc_',
  'dbuser' => 'oc_pcadmin',
  'dbpassword' => '1234...',
  'installed' => true,
  'tempdirectory' => '/home/pcadmin/nextcloudtemp',
  'loglevel' => 0,
);

/home/pcadmin/nextcloudtemp ==> chown -R www-data:www-data nextcloudtemp

+ Docker
  https://gridscale.io/community/tutorials/docker-ubuntu/
  apt-get install curl
  curl https://get.docker.com | bash
  systemctl status docker

+ OCR Janis91
  /var/www/nextcloud.../redis
    sudo docker build -t nextcloud/redis .
  /var/www/nextcloud.../worker
  sudo docker build -t nextcloud/ocr .

docker network create --driver bridge isolated_ocr
docker run --name redis --network=isolated_ocr -p 6379:6379 -d nextcloud/redis
docker run --name ocr --network=isolated_ocr -e "NODE_ENV=production" -e "REDIS_HOST=redis" -e "REDIS_PORT=6379" -e "REDIS_DB=0" -v /var/www/nextcloud/data:/home/node/data:ro -v /home/pcadmin/nextcloudtemp:/home/node/output -d nextcloud/ocr

2.
3.
4.

## Context

I try to install the docker container new (after deleting they before)

## Your Environment

* OCR version used:  3.1.0-beta.1
* Browser Name and version: Firefox and Edge under Windows 10
* Operating System and version (desktop or mobile): Windows 10
* ownCloud/nextcloud version: (see ownCloud admin page or version.php) 12.04 / 7.022
* PHP version 7.022
* Database version mariadbArt: mysql Version: 10.0.31 Größe: 2.1 MB
* Are you using encryption: yes/no ==> no

## Log File Content (nextcloud/owncloud.log of the "data"-directory)

{"reqId":"Lhspy6eE7T3mYy05jgdb","level":0,"time":"2017-12-22T15:44:19+00:00","remoteAddr":"192.168.2.36","user":"pcadmin","app":"no app in context","method":"GET","url":"\/nextcloud\/index.php\/apps\/ocr\/status","message":"Retrieved the following array from Redis: []","userAgent":"Mozilla\/5.0 (Windows NT 10.0; WOW64; rv:57.0) Gecko\/20100101 Firefox\/57.0","version":"12.0.4.3"}
{"reqId":"Lhspy6eE7T3mYy05jgdb","level":0,"time":"2017-12-22T15:44:19+00:00","remoteAddr":"192.168.2.36","user":"pcadmin","app":"no app in context","method":"GET","url":"\/nextcloud\/index.php\/apps\/ocr\/status","message":"Check if files were processed by ocr and if so, put them to the right dirs.","userAgent":"Mozilla\/5.0 (Windows NT 10.0; WOW64; rv:57.0) Gecko\/20100101 Firefox\/57.0","version":"12.0.4.3"}
{"reqId":"Lhspy6eE7T3mYy05jgdb","level":0,"time":"2017-12-22T15:44:19+00:00","remoteAddr":"192.168.2.36","user":"pcadmin","app":"no app in context","method":"GET","url":"\/nextcloud\/index.php\/apps\/ocr\/status","message":"Following jobs failed: []","userAgent":"Mozilla\/5.0 (Windows NT 10.0; WOW64; rv:57.0) Gecko\/20100101 Firefox\/57.0","version":"12.0.4.3"}
{"reqId":"7EmzOSdLjqKFmiAdIidb","level":0,"time":"2017-12-22T15:44:41+00:00","remoteAddr":"192.168.2.36","user":"pcadmin","app":"no app in context","method":"POST","url":"\/nextcloud\/index.php\/apps\/ocr","message":"Will now process files: [{\"id\":\"113\"}] with languages: [\"deu\"] and replace: false","userAgent":"Mozilla\/5.0 (Windows NT 10.0; WOW64; rv:57.0) Gecko\/20100101 Firefox\/57.0","version":"12.0.4.3"}
{"reqId":"aM3RmJt5iFixEX8yLpOT","level":0,"time":"2017-12-22T15:44:46+00:00","remoteAddr":"192.168.2.36","user":"pcadmin","app":"no app in context","method":"GET","url":"\/nextcloud\/index.php\/apps\/ocr\/status","message":"Retrieved the following array from Redis: []","userAgent":"Mozilla\/5.0 (Windows NT 10.0; WOW64; rv:57.0) Gecko\/20100101 Firefox\/57.0","version":"12.0.4.3"}
{"reqId":"aM3RmJt5iFixEX8yLpOT","level":0,"time":"2017-12-22T15:44:46+00:00","remoteAddr":"192.168.2.36","user":"pcadmin","app":"no app in context","method":"GET","url":"\/nextcloud\/index.php\/apps\/ocr\/status","message":"Check if files were processed by ocr and if so, put them to the right dirs.","userAgent":"Mozilla\/5.0 (Windows NT 10.0; WOW64; rv:57.0) Gecko\/20100101 Firefox\/57.0","version":"12.0.4.3"}
{"reqId":"aM3RmJt5iFixEX8yLpOT","level":0,"time":"2017-12-22T15:44:46+00:00","remoteAddr":"192.168.2.36","user":"pcadmin","app":"no app in context","method":"GET","url":"\/nextcloud\/index.php\/apps\/ocr\/status","message":"Following jobs failed: []","userAgent":"Mozilla\/5.0 (Windows NT 10.0; WOW64; rv:57.0) Gecko\/20100101 Firefox\/57.0","version":"12.0.4.3"}
pcadmin@nextcloud:~$ sudo tail /var/www/nextcloud/data/nextcloud.log
{"reqId":"OBfrnpYKZRCXbl6gNPvA","level":0,"time":"2017-12-22T15:44:55+00:00","remoteAddr":"192.168.2.36","user":"pcadmin","app":"no app in context","method":"GET","url":"\/nextcloud\/index.php\/apps\/ocr\/status","message":"Following jobs failed: []","userAgent":"Mozilla\/5.0 (Windows NT 10.0; WOW64; rv:57.0) Gecko\/20100101 Firefox\/57.0","version":"12.0.4.3"}
{"reqId":"DelGvSVId783PTFlqP6U","level":0,"time":"2017-12-22T15:45:00+00:00","remoteAddr":"192.168.2.36","user":"pcadmin","app":"no app in context","method":"GET","url":"\/nextcloud\/index.php\/apps\/ocr\/status","message":"Retrieved the following array from Redis: []","userAgent":"Mozilla\/5.0 (Windows NT 10.0; WOW64; rv:57.0) Gecko\/20100101 Firefox\/57.0","version":"12.0.4.3"}
{"reqId":"DelGvSVId783PTFlqP6U","level":0,"time":"2017-12-22T15:45:00+00:00","remoteAddr":"192.168.2.36","user":"pcadmin","app":"no app in context","method":"GET","url":"\/nextcloud\/index.php\/apps\/ocr\/status","message":"Check if files were processed by ocr and if so, put them to the right dirs.","userAgent":"Mozilla\/5.0 (Windows NT 10.0; WOW64; rv:57.0) Gecko\/20100101 Firefox\/57.0","version":"12.0.4.3"}
{"reqId":"DelGvSVId783PTFlqP6U","level":0,"time":"2017-12-22T15:45:00+00:00","remoteAddr":"192.168.2.36","user":"pcadmin","app":"no app in context","method":"GET","url":"\/nextcloud\/index.php\/apps\/ocr\/status","message":"Following jobs failed: []","userAgent":"Mozilla\/5.0 (Windows NT 10.0; WOW64; rv:57.0) Gecko\/20100101 Firefox\/57.0","version":"12.0.4.3"}
{"reqId":"NTKOFS62baXbwZn1E31x","level":0,"time":"2017-12-22T15:45:04+00:00","remoteAddr":"192.168.2.36","user":"pcadmin","app":"no app in context","method":"GET","url":"\/nextcloud\/index.php\/apps\/ocr\/status","message":"Retrieved the following array from Redis: []","userAgent":"Mozilla\/5.0 (Windows NT 10.0; WOW64; rv:57.0) Gecko\/20100101 Firefox\/57.0","version":"12.0.4.3"}
{"reqId":"NTKOFS62baXbwZn1E31x","level":0,"time":"2017-12-22T15:45:04+00:00","remoteAddr":"192.168.2.36","user":"pcadmin","app":"no app in context","method":"GET","url":"\/nextcloud\/index.php\/apps\/ocr\/status","message":"Check if files were processed by ocr and if so, put them to the right dirs.","userAgent":"Mozilla\/5.0 (Windows NT 10.0; WOW64; rv:57.0) Gecko\/20100101 Firefox\/57.0","version":"12.0.4.3"}
{"reqId":"NTKOFS62baXbwZn1E31x","level":0,"time":"2017-12-22T15:45:04+00:00","remoteAddr":"192.168.2.36","user":"pcadmin","app":"no app in context","method":"GET","url":"\/nextcloud\/index.php\/apps\/ocr\/status","message":"Following jobs failed: []","userAgent":"Mozilla\/5.0 (Windows NT 10.0; WOW64; rv:57.0) Gecko\/20100101 Firefox\/57.0","version":"12.0.4.3"}
{"reqId":"AYDwu2QIrXQPa9R92t0H","level":0,"time":"2017-12-22T15:45:09+00:00","remoteAddr":"192.168.2.36","user":"pcadmin","app":"no app in context","method":"GET","url":"\/nextcloud\/index.php\/apps\/ocr\/status","message":"Retrieved the following array from Redis: []","userAgent":"Mozilla\/5.0 (Windows NT 10.0; WOW64; rv:57.0) Gecko\/20100101 Firefox\/57.0","version":"12.0.4.3"}
{"reqId":"AYDwu2QIrXQPa9R92t0H","level":0,"time":"2017-12-22T15:45:09+00:00","remoteAddr":"192.168.2.36","user":"pcadmin","app":"no app in context","method":"GET","url":"\/nextcloud\/index.php\/apps\/ocr\/status","message":"Check if files were processed by ocr and if so, put them to the right dirs.","userAgent":"Mozilla\/5.0 (Windows NT 10.0; WOW64; rv:57.0) Gecko\/20100101 Firefox\/57.0","version":"12.0.4.3"}
{"reqId":"AYDwu2QIrXQPa9R92t0H","level":0,"time":"2017-12-22T15:45:09+00:00","remoteAddr":"192.168.2.36","user":"pcadmin","app":"no app in context","method":"GET","url":"\/nextcloud\/index.php\/apps\/ocr\/status","message":"Following jobs failed: []","userAgent":"Mozilla\/5.0 (Windows NT 10.0; WOW64; rv:57.0) Gecko\/20100101 Firefox\/57.0","version":"12.0.4.3"}

**Comment by janis91** [comment]
Please try again using the new version :)
