### ISSUE TITLE
Make Wiki writable

### ISSUE THREAD

**Issue by stweil** [janis91/ocr#135]
https://github.com/janis91/ocr/wiki currently cannot be edited by most users. As there are several issues (markdown format errors, wrong hyperlinks), I suggest to allow edits by registered GitHub users. A maintainer still can create a local wiki clone with git and remove unwanted modifications there.

**Comment by janis91** [comment]
done.

**Comment by stweil** [comment]
Great, thank you. I just made 5 commits for the Wiki.
