### ISSUE TITLE
App context missing for log messages from ocr app

### ISSUE THREAD

**Issue by stweil** [janis91/ocr#136]
The Nextcloud protocol does not show the correct app name _ocr_, but _no app in context_, for messages from the OCR app:

    {"reqId":"##","level":0,"time":"2018-02-24T07:42:30+00:00","remoteAddr":"##.##.##.##","user":"##","app":"no app in context","method":"GET","url":"\/index.php\/apps\/ocr\/status","message":"Following jobs failed: []","userAgent":"##","version":"##"}

**Comment by janis91** [comment]
fixed in #139
