### ISSUE TITLE
Overlapping elements in selected action list header

### ISSUE THREAD

**Issue by stweil** [janis91/ocr#142]
The latest version now shows again a selectable entry in the action list header as soon as at least one image or PDF was selected in the file view. That entry overlaps with other entries, so it cannot be selected.

**Comment by janis91** [comment]
For me this was also the case in the first place, but actually I updated the corresponding styles, is this maybe a caching problem? Or could you provide a screenshot? Because for me it is working :-)

**Comment by stweil** [comment]
It looks like this:

![ocr-app](https://user-images.githubusercontent.com/6734573/37253340-d3807b96-2530-11e8-91b4-24ab4f12387d.png)

**Comment by stweil** [comment]
Maybe this issue only occurs when Nextcloud was installed in a subdirectory (as in my installation)? See also my comment on issue #145.

**Comment by janis91** [comment]
Ok, no it's a translation related issue. I will try to fix it!

**Comment by janis91** [comment]
should be fixed

**Comment by stweil** [comment]
It is, thank you.
