### ISSUE TITLE
wrong redis settings format

### ISSUE THREAD

**Issue by celevra** [janis91/ocr#158]
hi,

i use the official nextcloud docker image, started your docker containers as follow:
```
docker run --name ocrredis --network=keen -d ocrredis
docker run --name ocr --network=keen -e "NODE_ENV=production" -e "REDIS_HOST=ocrredis" -e "REDIS_PORT=6379" -e "REDIS_DB=0" -e "REDIS_PASSWORD=xxx" -v /var/www/vhosts/cloud/data:/home/node/data:ro -v /tmp:/home/node/output -d ocr
```

if i set the settings like this:
![image](https://user-images.githubusercontent.com/232437/39445800-880c0780-4cbc-11e8-9324-24b2f952c755.png)
i get an error that the settings are wrong.
The nextcloud docker container is also in the keen network

regards

**Comment by shneezin** [comment]
Versuch es mal mit der IP Adresse des Redis Host´s.
Wenn du es wie in der Wiki Anleitung gemacht hast, kannst du die 127.0.0.1 oder localhost eintragen.
Solltest du jedoch weiterhin Probleme haben, warte einmal auf das nächste Update, da es gerade Probleme gibt mit der App/ Docker.

![bildschirmfoto 2018-05-01 um 20 52 15](https://user-images.githubusercontent.com/7408259/39488133-94bccc42-4d81-11e8-8986-1704f35e7aad.png)

**Comment by celevra** [comment]
hi,

danke für die Antwort, mit der IP geht es auch nicht. Da Nextcloud bei mir ebenfalls in einem Container läuft kann ich nicht 127.0.0.1 nutzen. Dann warte ich mal auf das Update ;-)

**Comment by shneezin** [comment]
Ok, das ergibt es Sinn. :)

**Comment by celevra** [comment]
Genau das hab ich gemacht, ne andere IP hatte für mich keinen Sinn ergeben ;-)


________________________________
Von: Janis Koehr <notifications@github.com>
Gesendet: Mittwoch, 2. Mai 2018 07:35
An: janis91/ocr
Cc: Philipp Zeitschel; Author
Betreff: Re: [janis91/ocr] wrong redis settings format (#158)


Hi, du kannst allerdings mal schauen, welche IP docker dem container intern vergibt und diese IP setzen. Mit docker inspect <container id> bekommst du die interne IP heraus (unter networking oder so ähnlich).

Aber es gibt tatsächlich leider irgendwelche Probleme mit dem Mapping der nextcloud daten in den OCR worker container. Ich bin da dran, habe leider aktuell noch keine Lösung.

**Comment by janis91** [comment]
I won't support anything prior version 4, because the whole setup is just too much effort. I will close this issue now and hope that version 4 (which will be shipped in a few weeks probably) will fill your need. If not. please feel free to fork the repo and work on the old code base which will reside in the branch "not-maintained".
