### ISSUE TITLE
ENOENT: no such file or directory, unlink error OCR

### ISSUE THREAD

**Issue by skyfreak1x** [janis91/ocr#160]
Hello Janis

I am Experiencing Issues with Setting up OCR for Nextcloud

I have followed the steps on the wiki
I have installed the pre-requisites required to run the service: PHP-Redis, OCRMyPdf, Tesseract-OCR, NPM, Python3-pip, PHP7.1 (already Installed by Nextcloud requirements), Nodejs.

Setup with the following commands:

sudo docker build --build-arg PASSWORD="secret" -t user/redis .
sudo docker build --build-arg LANGUAGES="tesseract-ocr-eng" -t user/ocr .

docker network create --driver bridge isolated_ocr

docker run --name redis --network=isolated_ocr --restart always -p 6379:6379 -d user/redis

docker run --name ocr --network=isolated_ocr --restart always -e "NODE_ENV=production" -e "REDIS_HOST=LANIP" -e "REDIS_PORT=6379" -e "REDIS_DB=0" -e "REDIS_PASSWORD=secret"  -v /var/www/html/next-data:/home/node/data:ro -v /var/www/html/nextcloud/tmp:/home/node/output -d user/ocr

Note: I have checked to make sure that the input path of the my data and temp exists and have permission for www-data

Redis Container Log
> 1:C 11 May 08:51:32.002 # oO0OoO0OoO0Oo Redis is starting oO0OoO0OoO0Oo
1:C 11 May 08:51:32.002 # Redis version=4.0.9, bits=64, commit=00000000, modified=0, pid=1, just started
1:C 11 May 08:51:32.002 # Configuration loaded
1:M 11 May 08:51:32.005 * Running mode=standalone, port=6379.
1:M 11 May 08:51:32.005 # WARNING: The TCP backlog setting of 511 cannot be enforced because /proc/sys/net/core/somaxconn is set to the lower value of 128.
1:M 11 May 08:51:32.005 # Server initialized
1:M 11 May 08:51:32.005 # WARNING overcommit_memory is set to 0! Background save may fail under low memory condition. To fix this issue add ‘vm.overcommit_memory = 1’ to /etc/sysctl.conf and then reboot or run the command ‘sysctl vm.overcommit_memory=1’ for this to take effect.
1:M 11 May 08:51:32.005 # WARNING you have Transparent Huge Pages (THP) support enabled in your kernel. This will create latency and memory usage issues with Redis. To fix this issue run the command ‘echo never > /sys/kernel/mm/transparent_hugepage/enabled’ as root, and add it to your /etc/rc.local in order to retain the setting after a reboot. Redis must be restarted after THP is disabled.
1:M 11 May 08:51:32.005 * Ready to accept connections
1:M 11 May 08:59:35.789 * 10 changes in 300 seconds. Saving…
1:M 11 May 08:59:35.789 * Background saving started by pid 13
13:C 11 May 08:59:35.934 * DB saved on disk
13:C 11 May 08:59:35.935 * RDB: 0 MB of memory used by copy-on-write
1:M 11 May 08:59:35.990 * Background saving terminated with success
1:M 11 May 09:04:36.042 * 10 changes in 300 seconds. Saving…
1:M 11 May 09:04:36.042 * Background saving started by pid 19
19:C 11 May 09:04:36.187 * DB saved on disk
19:C 11 May 09:04:36.188 * RDB: 0 MB of memory used by copy-on-write
1:M 11 May 09:04:36.243 * Background saving terminated with success
1:M 11 May 09:24:37.548 * 1 changes in 900 seconds. Saving…
1:M 11 May 09:24:37.548 * Background saving started by pid 20
20:C 11 May 09:24:37.638 * DB saved on disk
20:C 11 May 09:24:37.639 * RDB: 0 MB of memory used by copy-on-write
1:M 11 May 09:24:37.649 * Background saving terminated with success
1:M 11 May 09:29:38.025 * 10 changes in 300 seconds. Saving…
1:M 11 May 09:29:38.025 * Background saving started by pid 21
21:C 11 May 09:29:38.149 * DB saved on disk
21:C 11 May 09:29:38.150 * RDB: 0 MB of memory used by copy-on-write
1:M 11 May 09:29:38.226 * Background saving terminated with success
1:signal-handler (1526031313) Received SIGTERM scheduling shutdown…
1:M 11 May 09:35:13.664 # User requested shutdown…
1:M 11 May 09:35:13.664 * Saving the final RDB snapshot before exiting.
1:M 11 May 09:35:13.754 * DB saved on disk
1:M 11 May 09:35:13.754 * Removing the pid file.
1:M 11 May 09:35:13.754 # Redis is now ready to exit, bye bye…
1:C 11 May 09:35:16.287 # oO0OoO0OoO0Oo Redis is starting oO0OoO0OoO0Oo
1:C 11 May 09:35:16.287 # Redis version=4.0.9, bits=64, commit=00000000, modified=0, pid=1, just started
1:C 11 May 09:35:16.287 # Configuration loaded
1:M 11 May 09:35:16.289 * Running mode=standalone, port=6379.
1:M 11 May 09:35:16.289 # WARNING: The TCP backlog setting of 511 cannot be enforced because /proc/sys/net/core/somaxconn is set to the lower value of 128.
1:M 11 May 09:35:16.289 # Server initialized
1:M 11 May 09:35:16.289 # WARNING overcommit_memory is set to 0! Background save may fail under low memory condition. To fix this issue add ‘vm.overcommit_memory = 1’ to /etc/sysctl.conf and then reboot or run the command ‘sysctl vm.overcommit_memory=1’ for this to take effect.
1:M 11 May 09:35:16.293 # WARNING you have Transparent Huge Pages (THP) support enabled in your kernel. This will create latency and memory usage issues with Redis. To fix this issue run the command ‘echo never > /sys/kernel/mm/transparent_hugepage/enabled’ as root, and add it to your /etc/rc.local in order to retain the setting after a reboot. Redis must be restarted after THP is disabled.
1:M 11 May 09:35:16.293 * DB loaded from disk: 0.000 seconds
1:M 11 May 09:35:16.293 * Ready to accept connections
1:M 11 May 09:50:17.091 * 1 changes in 900 seconds. Saving…
1:M 11 May 09:50:17.091 * Background saving started by pid 18
18:C 11 May 09:50:17.182 * DB saved on disk
18:C 11 May 09:50:17.182 * RDB: 0 MB of memory used by copy-on-write
1:M 11 May 09:50:17.192 * Background saving terminated with success

OCR Container Log

>2018-05-11T09:03:40.950Z - error: Job errored: ENOENT: no such file or directory, unlink '/home/node/output/ocr_2D4bxi.pdf’
2018-05-11T09:24:41.000Z - error: Job errored: ENOENT: no such file or directory, unlink '/home/node/output/ocr_G9IL9t.pdf’
2018-05-11T09:28:28.898Z - error: Job errored: ENOENT: no such file or directory, unlink '/home/node/output/ocr_ra1Ktu.pdf’
2018-05-11T09:28:28.996Z - error: Job errored: ENOENT: no such file or directory, unlink '/home/node/output/ocr_KVsyFu.pdf’
2018-05-11T09:31:24.141Z - error: Job errored: ENOENT: no such file or directory, unlink '/home/node/output/ocr_z5a6DZ.pdf’
2018-05-11T09:35:13.757Z - warn: Connection closed to redis server.
2018-05-11T09:35:13.810Z - error: ERROR: read ECONNRESET.
2018-05-11T09:35:13.811Z - warn: Connection closed to redis server.
2018-05-11T09:35:13.912Z - error: ERROR: connect ECONNREFUSED IP:6379.
2018-05-11T09:35:13.913Z - warn: Connection closed to redis server.
2018-05-11T09:35:14.064Z - error: ERROR: connect ECONNREFUSED x:6379.
2018-05-11T09:35:14.065Z - warn: Connection closed to redis server.
2018-05-11T09:35:14.266Z - error: ERROR: connect ECONNREFUSED x:6379.
2018-05-11T09:35:14.267Z - warn: Connection closed to redis server.
2018-05-11T09:35:14.519Z - error: ERROR: connect ECONNREFUSED x6379.
2018-05-11T09:35:14.519Z - warn: Connection closed to redis server.
2018-05-11T09:35:14.821Z - error: ERROR: connect ECONNREFUSED x:6379.
2018-05-11T09:35:14.821Z - warn: Connection closed to redis server.
2018-05-11T09:35:15.173Z - error: ERROR: connect ECONNREFUSED x:6379.
2018-05-11T09:35:15.173Z - warn: Connection closed to redis server.
2018-05-11T09:35:27.924Z - error: Job errored: ENOENT: no such file or directory, unlink ‘/home/node/output/ocr_Mgb63x.pdf’

I accessed the OCR container directory and found that output folder did not have any file inside.

Can you help me Diagnose this problem of ocr not working

**Comment by janis91** [comment]
I sthere any reason why you sudo'ed when creating the docker containers?

**Comment by janis91** [comment]
I won't support anything prior version 4, because the whole setup is just too much effort. I will close this issue now and hope that version 4 (which will be shipped in a few weeks probably) will fill your need. If not. please feel free to fork the repo and work on the old code base which will reside in the branch "not-maintained".
