### ISSUE TITLE
spawnSync ocrmypdf ETIMEDOUT

### ISSUE THREAD

**Issue by hoangdmps02770** [janis91/ocr#162]
Hi,
I already get my ocr working just fine but I have got a problem while indexing big pdf file ( 10 more pages ). It returns a problem such as The execution of 'ocrmypdf' command failed: Error: spawnSync ocrmypdf ETIMEDOUT. How can I increase the ETIMEOUT ?
Thanks so much.

**Comment by janis91** [comment]
Hi, normally it shouldn't timeout at all, becaus the default timeout value is undefined. Do you have mor log information?

**Comment by hoangdmps02770** [comment]
This is recored in the nextcloud.log
{"reqId":"YR0xBfh4tDvT0UKr6XPT","level":3,"time":"2018-06-05T03:49:22+00:00","remoteAddr":"192.168.1.100","user":"admin","app":"OCR","method":"GET","url":"\/nextcloud\/index.php\/apps\/ocr\/status","message":"The execution of 'ocrmypdf' command failed: Error: spawnSync ocrmypdf ETIMEDOUT","userAgent":"Mozilla\/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit\/537.36 (KHTML, like Gecko) Chrome\/66.0.3359.181 Safari\/537.36","version":"13.0.2.1"}
{"reqId":"pmbyv2JVgb0VGh74Tx20","level":3,"time":"2018-06-05T03:52:38+00:00","remoteAddr":"192.168.1.100","user":"admin","app":"OCR","method":"GET","url":"\/nextcloud\/index.php\/apps\/ocr\/status","message":"The execution of 'ocrmypdf' command failed: Error: spawnSync ocrmypdf ETIMEDOUT","userAgent":"Mozilla\/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit\/537.36 (KHTML, like Gecko) Chrome\/66.0.3359.181 Safari\/537.36","version":"13.0.2.1"}

**Comment by janis91** [comment]
I won't support anything prior version 4, because the whole setup is just too much effort. I will close this issue now and hope that version 4 (which will be shipped in a few weeks probably) will fill your need. If not. please feel free to fork the repo and work on the old code base which will reside in the branch "not-maintained".
