### ISSUE TITLE
Docker build fails

### ISSUE THREAD

**Issue by kmorber** [janis91/ocr#164]
I have the following problem during build process of the docker

> node-ocr-worker@0.0.0 build /home/node/worker
> rm -rf dist/ && tsc -p tsconfig.app.json

src/configuration/worker.configuration.ts(7,28): error TS2322: Type '{ db: string | number; host: string; keyPrefix: string; password: string; port: string | number; ...' is not assignable to type 'RedisOptions'.
  Types of property 'port' are incompatible.
    Type 'string | number' is not assignable to type 'number'.
      Type 'string' is not assignable to type 'number'.

What is going wrong?

here are the commands i use:

  git clone https://github.com/janis91/ocr.git
  cd ocr
  cd redis
  docker build --build-arg PASSWORD="*************" -t kmorber/redis .
  docker network create --driver=bridge --subnet=172.18.0.0/24 isolated_ocr
  docker run --name=redis --net=isolated_ocr  --ip=172.18.0.5 -p 6378:6379 -d kmorber/redis
  cd ..
  cd worker
  docker build --build-arg LANGUAGES="tesseract-ocr-deu" -t kmorber/ocr .
  docker run --name=ocr -e "NODE_ENV=production" --network=isolated_ocr  -e "REDIS_HOST=redis" -e "REDIS_PORT=6379" -e "REDIS_DB=0" -e "REDIS_PASSWORD=**********" -v /opt/nextcloud/data:/home/node/data -v /opt/nextcloud/data/tmp:/home/node/output -d kmorber/ocr
 

 -->

# Bug report / Feature request
## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* OCR version used:
* Browser Name and version:
* Operating System and version (desktop or mobile):
* ownCloud/nextcloud version: (see ownCloud admin page or version.php)
* PHP version
* Database version
* Are you using encryption: yes/no

**Comment by kmorber** [comment]
Hello,

it worked for month, but since two days it is failing.

Best regards

**Comment by chriseqipe** [comment]
I'm not a node/npm pro but this litte fix https://github.com/janis91/ocr/pull/165 works for me

**Comment by fulljackz** [comment]
@chriseqipe Works fine, thanks !

**Comment by janis91** [comment]
I won't support anything prior version 4, because the whole setup is just too much effort. I will close this issue now and hope that version 4 (which will be shipped in a few weeks probably) will fill your need. If not. please feel free to fork the repo and work on the old code base which will reside in the branch "not-maintained".
