### ISSUE TITLE
Problems with OCR Docker Install for  Nextcloud in Ubuntu 18.4 Machine

### ISSUE THREAD

**Issue by Runcracker** [janis91/ocr#166]
**Unfixed Bug1** = Docker Containers are not boot resistant. Reboot Ubuntu and the Container and any settings are lost.  (Need Help)

**Important i need Help!**
**Unfixed Bug2** = Ive got info (when i ve not reboot ic can check all and redis is working with OCR container well) but when i scan Document i get Error :

"The execution of 'ocrmypdf' command failed: ERROR - File not found - /home/node/data/Nextdriveadmin/files/*******example*****.pdf" 

--
**Only for Notice: and you should know, actually in time App roll out with Syntax Error/Bug:**
One of the files for Create the OCR Docker it comes include the App in folder "Worker" have mistakes.
I have found bugfix by myself.
worker.configuration.ts have two wrong lines in code:
1: "db: process.env.REDIS_DB || 0,"  i ve  repaced with "db: parseInt(process.env.REDIS_DB) || 0,"
2: "port: process.env.REDIS_PORT || 6379," ive replaced with "port: parseInt(process.env.REDIS_PORT) || 6378,"
For the Port i have to change for all of this OCR Project because 6379 is already in use for Document Server and Only Office on same machine.
Without modifikation Docker Build break down, bacause npm get problems.

Please can help me? Please contact me werner.groenke "ett" googlemail "dot" com ,
perhaps you can help per team viewer , tell me how much is your service , because we need this cloud because its the one and only way, to go DSGVO conform. 

# Bug report / Feature request
## Expected Behavior

I've already change in docker and check the folders "docker exec – it CONTAINERID /bin/bash"
Result: 
Folder for temp avable and i can open
Folder Data i cant go in, because www-data is owner (so i cant check whats happen inside)

I've ask some Friends there are much better in Linux and Docker as me but we all have no more idea!

## Current Behavior

All settings and containers are lost by reboot system (any updates in future are unpossible? Wrong way)
When fresh installed redis is found and begin to scan than break down with told info.

* Rebootresistance of all around the Docker
* Found right directorys and can scan succesfully
* Bugfix the Mistake that comes include the App inside the  worker.configuration.ts.

## Possible Solution

Rights management in Docker Container. Perhaps write and read protection is wrong? Folder path in data is wrong?
90% of errors are sitting in time between chair and flatscreen? This all is really new for me! And i not think that i can and will learn all this in little time. 

## Steps to Reproduce (for bugs)

Iv installed any more times again , because can go back to snapshot before 
1.  i try first and often again : https://github.com/janis91/ocr/wiki/Installation-and-Configuration-(Docker-setup)
2. i try this : https://dasnetzundich.de/ocr-setup-fuer-nextcloud/
3. and many other i ve found in web

1a. Reboot system all Docker Containers and Settings are lost!

## Context

Unhappy, search for external help, should only still running and goal is not, to be a ubuntu and docker supervisor crack!

## Your Environment

* OCR version used: Latestd 2018/06/20
* Browser Name and version: Google Chrome Version 67.0.3396.87
* Operating System and version: Nextcloudhost is Ubuntu 18.4 
* ownCloud/nextcloud version: Nextcloud 13
* PHP version: 7.2
* Database version: Mariadb, Nginx, Apache2, Redis
* Are you using encryption: SSL Nextcloud & onlyOffice
* VM have 6GB Ram and 2TiB HDD in use

**Comment by janis91** [comment]
I won't support anything prior version 4, because the whole setup is just too much effort. I will close this issue now and hope that version 4 (which will be shipped in a few weeks probably) will fill your need. If not. please feel free to fork the repo and work on the old code base which will reside in the branch "not-maintained".

**Comment by e-alfred** [comment]
@janis91 Maybe https://github.com/daita/files_fulltextsearch_tesseract can replace this app?

**Comment by janis91** [comment]
@e-alfred Maybe. For me it fits in the gap between v4 of this app and what v3 was supposed to be originally. v3 was for distributed use cases and should have been a very scalable app. v4 is way easier from a developers perspective and will do all the work in the client. The app you mentioned seems to call tesseract-ocr on the server machine. So there is no option to scale this in a cloud scenario or similar and I am not quite sure if the server is blocked by the ocr process or how they manage to get it asynchronous, but I think it fits right in between my approaches and is a very valid idea. But I haven't tried it yet.

**Comment by e-alfred** [comment]
The advantage of a client-side only app would be that there are no changes needed on the server side (except installing the app) and no additional load caused on the server infrastructure. 

Fulltextsearch uses Elasticsearch as a backend so at least that part should be highly scalable. I am not sure about Tesseract though.

**Comment by janis91** [comment]
> The advantage of a client-side only app would be that there are no changes needed on the server side (except installing the app) and no additional load caused on the server infrastructure. 

Exactly. That is one reason why I decided to go this way.

> Fulltextsearch uses Elasticsearch as a backend so at least that part should be highly scalable. I am not sure about Tesseract though.

Tesseract is just a commandline tool. It may be spawned in multiple threads for example. But you need to take care of all the things.. feed it with the right inputs, schedule tasks, queue the workload, etc. 
It isn‘t impossible to scale tesseract, but it is not designed for getting connected to a queue or something like that..

**Comment by e-alfred** [comment]
I think two apps doing the same (server side) is not very useful, but a server side app (Fulltextsearch with Tesseract) and a completely client side app (like yours soon hopefully) would be great to fit different use cases well.
