### ISSUE TITLE
Compatibility with Nextcloud 14

### ISSUE THREAD

**Issue by ChristophWurst** [janis91/ocr#167]
Hi,

as you may have already seen, we have entered the beta phase for the release of Nextcloud 14. We usually try to keep up compatibility with previous app versions, but in some cases apps need some adjustments to properly work on new Nextcloud releases. With Nextcloud 14 there have been quite some changes in that regard:

You can find a list of all critical changes for app developers and admins at https://github.com/nextcloud/server/issues/7827. You can run occ app:check-code to validate that there are no issues with deprecated or private message calls.

One critical change is the overall restructuring of the main template (https://github.com/nextcloud/server/pull/9982) that might require some adjustments in your app.

We would be very pleased if you can make your app compatible with Nextcloud 14 and release a new version to the app store, so that users can properly test it and the upgrade experience to Nextcloud 14 will be even better than before.

Feel free to ask, if you have any questions regarding making your app compatible with Nextcloud 14.

Thanks for being part of the Nextcloud community and for all the effort you put into providing this app :rocket: .

**Comment by PietsHost** [comment]
any news on this?

**Comment by ChristophWurst** [comment]
I've got some news: there's already a beta of the next major version of Nextcloud: https://github.com/nextcloud/server/releases/tag/v15.0.0beta1

**Comment by PietsHost** [comment]
well, thank's @ChristophWurst but that's not helping me with the OCR App :D

**Comment by ChristophWurst** [comment]
sorry 🙃

@janis91 is this app still being maintained? Otherwise I'd suggest to give other members of our community the opportunity to take over the development and maintenance.

**Comment by janis91** [comment]
I will change the behaviour of the app while keeping the main purpose alive: ocr within nextcloud. But I won't be able to ship new features very often. What I do is, that I keep the code for the old v3 app in a branch "not-maintained" and strongly recommend to fork it and work on top of that, if you need an ocr that works asynchronously in the background of your nextcloud.
My current target for v4 is to bring in tesseract v4 in combination with tesseract-js and let the ocr process work in the client completely. That won't be a good enterprise solution, but currently this is what I can support at least.
