### ISSUE TITLE
OCR button not appearing

### ISSUE THREAD

**Issue by Brightside56** [janis91/ocr#180]
# Bug report
## Expected Behavior

After plugin installation I supposed to see OCR button in actions for selected PDFs/images
## Current Behavior

After plugin installation I don't see OCR button for PDF documents and images

## Your Environment

* OCR version used: 4.1.3
* Browser Name and version: Firefox latest
* Operating System and version (desktop or mobile): Ubuntu 18.04
* ownCloud/nextcloud version: Nextcloud 16.0.1
* PHP version 7.3
* Database version: Postgresql 11
* Are you using encryption: no

## Log File Content (nextcloud/owncloud.log of the "data"-directory AND console output of the browser)

There is nothing in log file which is OCR-app related 

I use Nextcloud docker images (fpm/alpine) with Caddy as webserver.

**Comment by Brightside56** [comment]
Are there some env. prerequisites for OCR app (packages e.t.c.)?

**Comment by janis91** [comment]
Thanks for your report. I am currently investigating.

**Comment by Brightside56** [comment]
> Thanks for your report. I am currently investigating.

To reproduce you need just fresh docker setup on alpine fpm container from nextcloud, then install app from nextcloud app store. If you need I can bootstrap fresh VM with exactly same setup and provide you root access

**Comment by janis91** [comment]
> > Thanks for your report. I am currently investigating.
> 
> To reproduce you need just fresh docker setup on alpine fpm container from nextcloud, then install app from nextcloud app store. If you need I can bootstrap fresh VM with exactly same setup and provide you root access

Thanks for your support. I think I fixed the original bug already. The final bundle of the app wasn't right. This is fixed. But while I was investigating, I found another bug, that I want to fix.
But if you installed nextcloud in the root directory of your server and not in a subdirectory, then 4.1.4 should already be available :-)

**Comment by janis91** [comment]
This should at latest be fixed with #181
