### ISSUE TITLE
/apps/ocr/vendor/tesseract.js/worker.min.js not found

### ISSUE THREAD

**Issue by Brightside56** [janis91/ocr#183]
404 on

https://xxxx.xxx/apps/ocr/vendor/tesseract.js/worker.min.js

after language selection. I use docker apline/fpm and caddy as webserver

My caddyfile is 

https://pastebin.com/raw/04xUf5VL

**Comment by janis91** [comment]
That sounds really like the problem I tried to solve a few minutes ago. could you give me the app version that is installed and the URL (you can leave it anonymous) for your nextcloud (for example to the files app)?

**Comment by Brightside56** [comment]
> That sounds really like the problem I tried to solve a few minutes ago. could you give me the app version that is installed and the URL (you can leave it anonymous) for your nextcloud (for example to the files app)?

I can't because it's also behind firewall, but I managed to figure out that there are no /var/www/html/apps/ocr dir. Also I can't reproduce this issue on second instance of nextcloud

App reinstallation doesn't helps same as recursive chown/chmod

**Comment by Brightside56** [comment]
@janis91 , I've found app files in /var/www/html/custom_apps/ocr. Nextcloud puts app files in custom_apps (not apps) for some reason, but app is trying to search its files in apps

**Comment by janis91** [comment]
I am not quite sure.. actually. How do you access your nextcloud from the browser? For me it is for example: `http://localhost:8080/index.php/apps/files/`
for others it's like: `https://something.com/nextcloud/apps/files/`
or even: `https://something.com/apps/files/`

What is right for yours?

And could you look up the "appinfo/info.xml" and give me the version of the currently installed app?

**Comment by janis91** [comment]
Ok now I looked into the docker installation and yes there is this "custom_apps" path, that is for 3rd party apps. Wow. I have to further investigate on this. I am really not sure, how to solve that.
