### ISSUE TITLE
Translation string extraction problem

### ISSUE THREAD

**Issue by janis91** [janis91/ocr#191]
Translation string extraction seems not to work since 4 days. Do you have any insight @MorrisJobke ? Nextcloud Bot also doesn't push already translated and reviewed translations.

If I can help with something, please let me know.

**Comment by MorrisJobke** [comment]
There it is: https://github.com/janis91/ocr/commit/7f7b09f0a17bb9364be69c2f45bf4d3b7740ceb8

Background: that many strings have changed that the translation ratio was below the threshold and thus the sync job deleted them all. This also deleted the `l10n` folder. If this folder is not present the sync job assumes that this is not a nextcloud app and doesn't start at all. Adding a `l10n/.gitkeep` file will make the folder not vanish and thus the job to always run.

**Comment by janis91** [comment]
Ah. That makes sense. Perfect. Thank you for the quick fix :-)
