### ISSUE TITLE
PDFs looking smoothed

### ISSUE THREAD

**Issue by smartbyte** [janis91/ocr#207]
It looks like the OCR is "mudding" my PDFs.

I am scanning my PDFs with 300 dpi, and after OCR did it's job it looks like the PDFs are sampled down to 150 dpi.

# Bug report
## Expected Behavior
The expected behavior would be that the system does not change the quality of the underlying PDF. 

## Current Behavior
The quality of the PDF changed significantly
The PDF file size changed from 16 down to 8 MB with a quality loss

## Possible Solution
A configuration option with which the user can set a default dpi (in my example 300)

## Steps to Reproduce (for bugs)
Scan a document with more than 150 dpi (e.g. 600) an let the OCR run, and check the quality / dpi afterwards-

## Context
Nextcloud 16.0.3

**Comment by janis91** [comment]
I will look into this. I already have an idea of where the issue could be.
Just to clarify: You do a scan of a document with 300 dpi and the scanned document is a PDF (not an image like jpeg or png) and then you process it with the app?

**Comment by janis91** [comment]
One more question: where do you look at the resulting pdf? Can you maybe provide screenshots of both: input and output and if it's possible with Adobe Acrobat Reader?

**Comment by smartbyte** [comment]
In my case I used Google Chrome to look at the before an after PDF. I will upload two screenshots showing the difference. But one fact was that the file size changed from 16MB to 8 MB, so the OCR must do "something" with the embedded pictures... (I am using ocrmypdf on the command line and it has a switch to set the dpi (not important), but another switch to _not_ touch the embedded images in a PDF, and that's what I would have expected.
Anyway, I will send the screenshots later on.
