### ISSUE TITLE
configurable file name extension

### ISSUE THREAD

**Issue by dt64** [janis91/ocr#227]
currently OCR'd PDFs get a new name like filename-ocr.pdf. (if the oroginal is kept)

would be great if that "-ocr" was configurable.

Reason:
running an installation where documents are OCR'd in a batch bei cron or manually, depending on usecase. These processes add their own extention in a similar way.
If now a new file is uploaded requiring instant OCRing is gets the "-ocr" extension and if the batch runs another one is created with the other processes extension.
The batch processes will OCR any file which doesn't have an equivalent file with their own extension...

**Comment by janis91** [comment]
PDF is no longer supported within this app. Probably there will be an additional app to modify PDF documents.
