### ISSUE TITLE
crash in tesseract

### ISSUE THREAD

**Issue by violoncelloCH** [janis91/ocr#230]
# Bug report
## Expected Behavior
ocr should process my screenshot.png and give me a text output

## Current Behavior
ocr crashes with "text recognition: text recognition failed: "an unexpected error happened while processing through tesseract."

## Steps to Reproduce (for bugs)
1. try to process a screenshot (4k Monitor with attached second FullHD Monitor)
2. select your languages (tried german and english and only german... behaviour was the same
3. don't select the checkmark to replace the original file
4. hit go and see it crashing (see logs)... the first time it took some more time, now it crashes after a few seconds

## Your Environment
* OCR version used: 4.4.14
* Browser Name and version: Firefox 69.0.2
* Operating System and version (desktop or mobile): Manjaro Linux with Gnome (stable, rolling release)
* nextcloud version: 16.0.5
* PHP version: 7.2
* Are you using encryption: no

## Logs (console output of the browser)
```
An error occured in OCR. Error: "Ein unerwarteter Fehler trat bei der Verarbeitung durch Tesseract auf."
    <anonymous> https://cloud.example.com/apps/ocr/js/app.js?v=0fe89a5c-37:1
    <anonymous> https://cloud.example.com/apps/ocr/js/app.js?v=0fe89a5c-37:8
    process https://cloud.example.com/apps/ocr/js/app.js?v=0fe89a5c-37:8
    c https://cloud.example.com/apps/ocr/js/app.js?v=0fe89a5c-37:8
 
{…}
​
err: "abort(\"Cannot enlarge memory arrays. Either (1) compile with  -s TOTAL_MEMORY=X  with X higher than the current value 268435456, (2) compile with  -s ALLOW_MEMORY_GROWTH=1  which allows increasing the size at runtime, or (3) if you want malloc to return NULL (0) instead of this abort, compile with  -s ABORTING_MALLOC=0 \"). Build with -s ASSERTIONS=1 for more info."
```

**Comment by janis91** [comment]
It seems that Tesseract.js is the bottleneck here. The underlying tesseract webassembly worker gets not enough memory. The only advise I can give is, that you can try to resize the screenshot to a smaller image.

**Comment by violoncelloCH** [comment]
thanks for your answer!
so there is no possibility to tell the browser to allow Tesseract.js to take up more memory?

**Comment by janis91** [comment]
I think it's not necessarily the browser who gives enough memory, maybe even the compile options of tesseract.js are the reason. @jeromewu could you maybe give advice here?

**Comment by jeromewu** [comment]
Well, tesseract.js is allowed to take as much memory as possible. But the hard limit for emscripten is now 2 GB, and the author is working to extend it to 4 GB in the future.

https://github.com/emscripten-core/emscripten/issues/6566
