### ISSUE TITLE
Bug: support multiple Files

### ISSUE THREAD

**Issue by aslmx** [janis91/ocr#231]
Support multiple file selections for OCR Conversion

I have huge amount of PDFs of invoices that i photo-scanned, processed into PDFs and stored them in NC. 

For new documents i can directly let them run through OCR (altough an automatic conversion or support for OCR conversion from the Android app in general would be nice!). 

If i have  folder with, lets say, 5 PDFs, i have to manually click the "..." menu and choose "OCR". Then i have to select the language (somebody already proposed a setting for this) and click "Process".

Proposal: support the selection of multiple Files

When a user selects two or more files, he can choose some action.
![nextcloud](https://user-images.githubusercontent.com/13053017/67084250-e32bc700-f19c-11e9-9068-f4b9adb25590.png)

Is it possible to put a "OCR process selected files" into the action Menu?

Thanks for considering!

**Comment by backamblock** [comment]
+1 on this one as well
this would be a huge time saver

**Comment by janis91** [comment]
This feature used to be available before v17 in nextcloud. Obviously it doesn't anymore. I will try to find the reason.
