### ISSUE TITLE
Replace files with filetype extension in uppercase

### ISSUE THREAD

**Issue by KarstenDE** [janis91/ocr#240]
# Bug report
## Expected Behavior
If I choose „replace the file” while ocring, the exact current filename should be used.

## Current Behavior
If the filetype extension is in uppercase (*.PDF) a second file is created with the extension in lower case (*.pdf).  
So defacto the replace option does not work for me.  
My scanner generate the file with completely uppercase filename.

## Possible Solution
Use the filename as it is.

## Steps to Reproduce (for bugs)
1. Create FILE.PDF
2. OCR with replace option
3. >> You got a second file FILE.pdf

## Your Environment
* OCR version used: 4.4.25
* Browser Name and version: Chrome
* Operating System and version (desktop or mobile): Windows 10
* nextcloud version: (see admin page or version.php) 17.0.0.1
* PHP version
* Database version
* Are you using encryption: no

**Comment by xsus95** [comment]
Same problem die me :)
