### ISSUE TITLE
Support for Nextcloud v18?

### ISSUE THREAD

**Issue by Schmuuu** [janis91/ocr#245]
Hello,

I would like to ask for support for NC18.
Currently, this app is still showing the following message in the apps list:

```
This app cannot be installed because the following dependencies are not fulfilled:
   - Server version 17 or lower is required. 
```

Thanks in advance and keep up the good work.
And thank you for this app!

**Comment by janis91** [comment]
I work on it. Unfortunately ,not finished yet.
