### ISSUE TITLE
Feature request - add option to read text on PDF that have been scanned in.

### ISSUE THREAD

**Issue by sh2515** [janis91/ocr#256]
# Feature request
Can you put back on the app PDF processing please? Really useful when I have to scan I. Documents to search.

**Comment by janis91** [comment]
It's very unlikely, that this will be available in the future again. It was way to complicated to get the pdf to pdf part working in a good way. (see: #251) The plan is to add another app that supports pdf handling. But not pdf ocr. Such that a future workflow for scanning documents is containing more steps:
1. Scan into png, jpeg or tiff
2. Ocr with this app
3. Merge individual pages with https://github.com/janis91/pdf_tailor

Hope this will help to solve all issues with the prior solution.
