### ISSUE TITLE
Not show OCR in PDF file

### ISSUE THREAD

**Issue by bkyceh** [janis91/ocr#257]
ocr is displayed only in jpg, not in pdf

After update to NC 18

## Your Environment

* OCR version used:6.0.2	
* Browser Name and version:Google Chrome Version 80.0.3987.87 (Official Build) (64-bit)
* Operating System and version (desktop or mobile):windows 10 pro
* nextcloud version: 18.0.0.10 
* PHP version 7.2.24
* Database version mysql 10.1.44
* Are you using encryption: no

**Comment by koenr** [comment]
Yes, same here
Nextcloud 17.0.3,Chrome 77.0.3865.75 (Officiële build) (64-bits) on Ubuntu 18.04
Since update to OCR 6.0.2

**Comment by janis91** [comment]
I don‘t get what you mean actually. Could you be more precise, please?

**Comment by bkyceh** [comment]
![da](https://user-images.githubusercontent.com/39523370/74355843-acb62f80-4dbd-11ea-97f8-ee9ea398783e.jpg)
![ne](https://user-images.githubusercontent.com/39523370/74355845-ade75c80-4dbd-11ea-96d3-06281feda2b9.jpg)

**Comment by koenr** [comment]
The menu for OCR is missing for PDF-documents (see screenshot)

![Schermafdruk van 2020-02-12 17-32-09](https://user-images.githubusercontent.com/2964998/74355825-a922a880-4dbd-11ea-8fcc-fad877883cd3.png)

**Comment by janis91** [comment]
Like stated in the app readme and description in the app store and further argued here: https://github.com/janis91/ocr/issues/256#issuecomment-584511299
This is not a bug. It‘s a full-stop of an approach that didn‘t work really well. Therefore I started another approach, which is not yet implemented completely. If you want to have pdf support in the mean time, use v5 of the app.

**Comment by koenr** [comment]
Ah, sorry. Didn't see the previous report since it was closed.

**Comment by bkyceh** [comment]
Sorry.  Didn't see.

**Comment by janis91** [comment]
No problem :-)

**Comment by medaemon** [comment]
thank you for the info and your work
 (I bet that PDF is the most used format for OCR  good luck for your new approach ;)

**Comment by janis91** [comment]
@medaemon you're welcome. Well since tesseract does not support pdf as input format, I think the new approach is much more beneficial in terms of file size and processing time.

**Comment by alexander-rieder** [comment]
ok, so any news on the new approach?

**Comment by TheEagle13** [comment]
Is there any update or other workaround besides using v5? If I try to install v5, Nextcloud tells me it's incompatible and needs to be updated or it won't let me use my instance.

**Comment by Schleichmichl** [comment]
I would even donate some euros to have this feature. OCR for big PDF files is so important. Are there any updates?
