### ISSUE TITLE
Translations not updated

### ISSUE THREAD

**Issue by janis91** [janis91/ocr#263]
# Bug report
## Expected Behavior

Nextcloud-bot pushes reviewed translations from transifex to the repository.

## Current Behavior

Nextcloud-bot did not push since 6 days. And there is an improved and more up to date translation available (also reviewed) in transifex. For example for: https://github.com/janis91/ocr/blob/9be1177e30e0e2ed4379afc50253cc506abcdc02/l10n/de.js#L84

## Possible Solution
Misconfiguration of CI

## Context

@ juliushaertl you set up the CI for my other app these days and it worked. Do you have an idea, why it stopped working for this app 6 days ago? Actually, I just don‘t know where to look at. Is there a log for the CI, etc?
Thank you!

**Comment by juliushaertl** [comment]
Just seen that in our transifex overview, could you check if the bot is able to push to master for this repo as the push fails due to a protected branch hook.

**Comment by janis91** [comment]
Thank you for that hint. The bot is still collaborator, but I set up a branch protection rule, that declined the push. Now it should work again. Thank you!
