### ISSUE TITLE
OCR function disapear after upgrade to nextcloud 18.0.1

### ISSUE THREAD

**Issue by medaemon** [janis91/ocr#269]
# Bug report
## Expected Behavior
When I click on the "..." the OCR butotn should appear to propose to launch the OCR process on the file.

## Current Behavior
The OCR function disapear from the menu

## Steps to Reproduce (for bugs)
Upgrade fro mnextcloud 17.0.3 with OCR 6.0.17 installed to nextcloud 18.0.1

## Context
Trying to OCR documents

## Your Environment
Upgraded version of nextcloud from 17.0.3 to 18.0.1 with OCR app already installed and correctly working before upgrade.
I have tried to disable reenable OCR app, change setting to limit to group (to try to refresh info somewhere) it does not change anything.

* OCR version used: 6.0.17
* Browser Name and version: Chrome 79
* Operating System and version (desktop or mobile): Win 10
* nextcloud version: (see admin page or version.php) 18.0.1
* PHP version 7.3
* Database version
* Are you using encryption: no

**Comment by janis91** [comment]
Which kind of document do you try to process? Pdf?

**Comment by medaemon** [comment]
Yes PDF files

**Comment by janis91** [comment]
https://github.com/janis91/ocr/issues/257#issuecomment-585296871
