### ISSUE TITLE
Update compatible version to 11

### ISSUE THREAD

**Issue by MorrisJobke** [janis91/ocr#29]
See https://github.com/nextcloud/server/pull/2139

To properly work with Nextcloud 11+ the `appinfo.xml` needs following entry in the `<dependencies>` tag (of course adjust the numbers to the ones that actually work ;)):

```xml
<nextcloud min-version="9" max-version="11" />
```

cc @janis91

**Comment by janis91** [comment]
Does this mean the following tag has to be deleted:
`<owncloud min-version="9.1" max-version="9.2" />`

Because the <nextcloud> tag is already available.

cc @MorrisJobke

**Comment by MorrisJobke** [comment]
> Does this mean the following tag has to be deleted:

If your app doesn't support owncloud ;) But to be on the save side simply leave both there - it uses the nextcloud one first and then checks for the owncloud one.
