### ISSUE TITLE
OCR processing does not support shared folders

### ISSUE THREAD

**Issue by rosperling** [janis91/ocr#36]
# Bug report / Feature request
## Expected Behavior

A file in a folder shared by another user should be able to be processed by the OCR app. 
## Current Behavior

Currently you may select files shared by other users and start the OCR process but it never finishes since the file is not accessible via nextcloud/data/user/current_user/files.
## Possible Solution

There are two possilbe solutions: 1st: disallow OCR processing of shared files or 2nd implement a possibility to find out the real path of the file to process - and if writable by the current user, process it.
## Steps to Reproduce (for bugs)

1. Share a directory of user A to user B, writeable.
2. Put a PDF in it.
3. Log in as user B, select the file and
4. choose OCR from the context menu.

## Your Environment

* OCR version used: 2.0.0
* Browser Name and version: All
* Operating System and version (desktop or mobile): Linux/Mac
* ownCloud/nextcloud version: Nextcloud 11
* php 7
* mysql
* Are you using encryption: no

## Log File Content (nextcloud/owncloud.log of the "data"-directory)
OCRWorker outputs "ERROR - File not found"

**Comment by janis91** [comment]
Thanks for figuring this out. I will come back to this issue as soon as I can - probably next week.

**Comment by janis91** [comment]
shared files are now considered by the app. thank you for your bug report! will upload the release to the app store in a few moments.
