### ISSUE TITLE
OCR 2.0.0 does not regonize deu-frak

### ISSUE THREAD

**Issue by Sanookmakmak** [janis91/ocr#37]
Nextcloud 11.0.0 on Ubuntu 16.04, java 1.8.0_111
Nextant 0.10.4, OCRmyPDF 4.3.3, tesseract-ocr 3.04.01

`apt-get install tesseract-deu-frak`

deu-frak does not appear in the list of installed languages

![9a3a5d95c1859bce0b2717b7b0ad3b708529f0f5](https://cloud.githubusercontent.com/assets/24833757/21608922/d63644c6-d1bf-11e6-8377-57a1d14572f7.png)

**Comment by janis91** [comment]
Fix will be in #39. thank you for reporting!
