### ISSUE TITLE
wiki supervisor example needs www-data user

### ISSUE THREAD

**Issue by jasonehines** [janis91/ocr#41]
# Bug report 
Following the [Supervisord](https://github.com/janis91/ocr/wiki/Configuration-and-Usage#usage-with-supervisor) example results in the file sitting in the queue.

## Expected Behavior
To process the files

## Current Behavior
The file stays in a pending mode
## Possible Solution
I added `user=www-data` to supervisord.conf which fixed it.

## Steps to Reproduce (for bugs)
Install per current instructions

## Your Environment

* OCR version used: 2.0
* Browser Name and version: Chrome 55.0.2883.87 (64-bit)
* Operating System and version (desktop or mobile): elementaryOS Loki
* ownCloud/nextcloud version: 11.0.1 (stable)
* PHP version: 7.0.13-0ubuntu0.16.10.1 
* Database version: mysql  Ver 14.14 Distrib 5.7.17
* Are you using encryption: no

**Comment by janis91** [comment]
Thank You! Actually I didn't think of the user. I updated the wiki already.
