### ISSUE TITLE
supervisor example needs process name

### ISSUE THREAD

**Issue by jasonehines** [janis91/ocr#42]
I probably should have added this to the other issue (oops).

I forget the exact error but since you are specifying multiple processes you have to specify `process_name` This is what worked for me: `process_name = %(program_name)s_%(process_num)02d` 

And this is the output of `servervisorctl status`:
`myworker:myworker_00             RUNNING   pid 2223, uptime 0:12:02`
`myworker:myworker_01             RUNNING   pid 2240, uptime 0:12:02`
`myworker:myworker_02             RUNNING   pid 2241, uptime 0:12:02`

**Comment by janis91** [comment]
Updated the supervisor example accordingly. I tested it.
