### ISSUE TITLE
[Feature request]: OCR a folder

### ISSUE THREAD

**Issue by Sanookmakmak** [janis91/ocr#47]
OCR 2.0.0

## Expected Behavior
Mark a folder and say OCR it

## Current Behavior
Cannot OCR a folder

**Comment by janis91** [comment]
As I mentioned in the forum, it might take some time to evaluate the effort and to implement this. But I will look into it, as soon as I can. Maybe it is not that big effort, but I don't know exactly. Also as [Stuart_Naylor](https://help.nextcloud.com/t/nc11-ocr-2-0-0-how-to-ocr-a-folder/7056/3?u=janis91) mentioned: Folders are a little bit tricky, as they may contain other files, which are not supported by tesseract or ocrmypdf. This would require some checks and so on. 

But I will look into it.

**Comment by MarcelWaldvogel** [comment]
A first start might be to only OCR PDFs that have no text associated with them.

I was installing the Nextcloud app for having all my documents automatically OCRed. So an extension would be to have a folder where any file which is added would automatically be OCRed. To avoid having the problem of re-OCR-ing files, the OCR version could replace the other one (and the above-mentioned need to have no text associated would break the loop).

(That probably would imply that there would need to be a default language(s) setting in the user settings.)

**Comment by janis91** [comment]
Will be part of #79 but for now I will add it as the following:
The folder itself cannot be ocred by a click on it or something like that.
BUT: you will be able to switch to the content of the folder and mark all files by the checkbox in the files top bar. After that the ocr option will be displayed. The app will then only process the files tesseract and ocrmypdf are supporting.
Hope that is a good first attempt. As the "right" folder processing will be a little bit mor tricky and maybe added later.
