### ISSUE TITLE
[Feature Request] Testing and Release for NC 12

### ISSUE THREAD

**Issue by janis91** [janis91/ocr#53]
# New release
Have a new branch available which is ready for the latest nextcloud 12.

For example there is a new feature available:
https://github.com/nextcloud/server/pull/3151

**Comment by janis91** [comment]
add the appicon as "Screenshot" in order to have a beautiful eye-catcher

**Comment by THS-on** [comment]
I've tested the latest version with the new NC beta and the normal ocr process works fine, but the settings are not shown in the personal menu(one item in queue):
![ocr](https://cloud.githubusercontent.com/assets/10854414/25775915/c121d346-32b0-11e7-86ac-eca136540e45.png)

**Comment by janis91** [comment]
Maybe this is a javascript error. But I will take of the next major update soon. Then I probably will have also another javascript structure, as I am currently refactoring the whole js code. I will test it and try to consider it there. Thanks for testing!

**Comment by THS-on** [comment]
I think it's a javacript error:
```
TypeError: Backbone is undefined[Weitere Informationen]  ocrpersonalview.js:43:5

TypeError: OC.Settings.Ocr.View is not a constructor[Weitere Informationen]  ocrpersonal.js:18:20
```
I think that this function not working so not so problematic, because the main part works still. I'll test the new code when it's ready.

**Comment by janis91** [comment]
Ok thanks for this console output. I think I know what's probably wrong here. I guess the Backbone library is not available anymore in nc 12. I will remove this dependent code (OC.Settings.Ocr.View as a constructor for the settings page) anyway in the next version, so this should be solved with the next update.

**Comment by janis91** [comment]
Related to #79

**Comment by janis91** [comment]
#90 merged. The pre-release for NC12 is out for testing. Thx for supporting me guys!

**Comment by THS-on** [comment]
It's working fine on my setup. I've tested not all features yet but basic functionality works (OCR images)
