### ISSUE TITLE
Error when trying to process a pdf

### ISSUE THREAD

**Issue by lordrascal** [janis91/ocr#58]
# Bug report 
## Your Environment

* OCR version used: 2.3.0
* Browser Name and version: Chrome 56.0.2924.87 (64 bit)
* Operating System and version (desktop or mobile): Windows 10 Pro 1607 / build: 14393.693
* nextcloud version: 11.0.1
* PHP version: 7.0.13-0ubuntu0.16.04.01
* Database version: mysql Ver 14.14 Distrib 5.7.17
* Are you using encryption: no

## Log File Content (nextcloud/owncloud.log of the "data"-directory)
`Error	index	OCP\AppFramework\Db\DoesNotExistException: Did expect one result but found none when executing: query "SELECT file_target FROM *PREFIX*share WHERE file_source = ? AND share_with = ? AND uid_owner = ?"; parameters Array ( [0] => 13392691 [1] => rascal [2] => local::/home/ ) ; limit ""; offset ""
/var/www/nextcloud/lib/public/AppFramework/Db/Mapper.php - line 373: OCP\AppFramework\Db\Mapper->findOneQuery('SELECT file_tar...', Array, NULL, NULL)
/var/www/nextcloud/apps/ocr/lib/Db/ShareMapper.php - line 42: OCP\AppFramework\Db\Mapper->findEntity('SELECT file_tar...', Array)
/var/www/nextcloud/apps/ocr/lib/Service/OcrService.php - line 320: OCA\Ocr\Db\ShareMapper->find('13392691', 'rascal', 'local /home/')
/var/www/nextcloud/apps/ocr/lib/Service/OcrService.php - line 173: OCA\Ocr\Service\OcrService->buildTargetForShared(Object(OCA\Ocr\Db\File))
/var/www/nextcloud/apps/ocr/lib/Controller/OcrController.php - line 74: OCA\Ocr\Service\OcrService->process(Array, Array)
/var/www/nextcloud/apps/ocr/lib/Controller/Errors.php - line 35: OCA\Ocr\Controller\OcrController->OCA\Ocr\Controller\{closure}()
/var/www/nextcloud/apps/ocr/lib/Controller/OcrController.php - line 75: OCA\Ocr\Controller\OcrController->handleNotFound(Object(Closure))
[internal function] OCA\Ocr\Controller\OcrController->process(Array, Array)
/var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php - line 160: call_user_func_array(Array, Array)
/var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php - line 90: OC\AppFramework\Http\Dispatcher->executeController(Object(OCA\Ocr\Controller\OcrController), 'process')
/var/www/nextcloud/lib/private/AppFramework/App.php - line 114: OC\AppFramework\Http\Dispatcher->dispatch(Object(OCA\Ocr\Controller\OcrController), 'process')
/var/www/nextcloud/lib/private/AppFramework/Routing/RouteActionHandler.php - line 47: OC\AppFramework\App main('OcrController', 'process', Object(OC\AppFramework\DependencyInjection\DIContainer), Array)
[internal function] OC\AppFramework\Routing\RouteActionHandler->__invoke(Array)
/var/www/nextcloud/lib/private/Route/Router.php - line 299: call_user_func(Object(OC\AppFramework\Routing\RouteActionHandler), Array)
/var/www/nextcloud/lib/base.php - line 1010: OC\Route\Router->match('/apps/ocr')
/var/www/nextcloud/index.php - line 40: OC handleRequest()
{main}
2 minutes ago
Error	ocr	Exception during ocr service function processing: {"Exception":"OCP\\AppFramework\\Db\\DoesNotExistException","Message":"Did expect one result but found none when executing: query \"SELECT file_target FROM *PREFIX*share WHERE file_source = ? AND share_with = ? AND uid_owner = ?\"; parameters Array\n(\n [0] => 13392691\n [1] => rascal\n [2] => local::\/home\/\n)\n; limit \"\"; offset \"\"","Code":0,"Trace":"#0 \/var\/www\/nextcloud\/lib\/public\/AppFramework\/Db\/Mapper.php(373): OCP\\AppFramework\\Db\\Mapper->findOneQuery('SELECT file_tar...', Array, NULL, NULL)\n#1 \/var\/www\/nextcloud\/apps\/ocr\/lib\/Db\/ShareMapper.php(42): OCP\\AppFramework\\Db\\Mapper->findEntity('SELECT file_tar...', Array)\n#2 \/var\/www\/nextcloud\/apps\/ocr\/lib\/Service\/OcrService.php(320): OCA\\Ocr\\Db\\ShareMapper->find('13392691', 'rascal', 'local::\/home\/')\n#3 \/var\/www\/nextcloud\/apps\/ocr\/lib\/Service\/OcrService.php(173): OCA\\Ocr\\Service\\OcrService->buildTargetForShared(Object(OCA\\Ocr\\Db\\File))\n#4 \/var\/www\/nextcloud\/apps\/ocr\/lib\/Controller\/OcrController.php(74): OCA\\Ocr\\Service\\OcrService->process(Array, Array)\n#5 \/var\/www\/nextcloud\/apps\/ocr\/lib\/Controller\/Errors.php(35): OCA\\Ocr\\Controller\\OcrController->OCA\\Ocr\\Controller\\{closure}()\n#6 \/var\/www\/nextcloud\/apps\/ocr\/lib\/Controller\/OcrController.php(75): OCA\\Ocr\\Controller\\OcrController->handleNotFound(Object(Closure))\n#7 [internal function]: OCA\\Ocr\\Controller\\OcrController->process(Array, Array)\n#8 \/var\/www\/nextcloud\/lib\/private\/AppFramework\/Http\/Dispatcher.php(160): call_user_func_array(Array, Array)\n#9 \/var\/www\/nextcloud\/lib\/private\/AppFramework\/Http\/Dispatcher.php(90): OC\\AppFramework\\Http\\Dispatcher->executeController(Object(OCA\\Ocr\\Controller\\OcrController), 'process')\n#10 \/var\/www\/nextcloud\/lib\/private\/AppFramework\/App.php(114): OC\\AppFramework\\Http\\Dispatcher->dispatch(Object(OCA\\Ocr\\Controller\\OcrController), 'process')\n#11 \/var\/www\/nextcloud\/lib\/private\/AppFramework\/Routing\/RouteActionHandler.php(47): OC\\AppFramework\\App::main('OcrController', 'process', Object(OC\\AppFramework\\DependencyInjection\\DIContainer), Array)\n#12 [internal function]: OC\\AppFramework\\Routing\\RouteActionHandler->__invoke(Array)\n#13 \/var\/www\/nextcloud\/lib\/private\/Route\/Router.php(299): call_user_func(Object(OC\\AppFramework\\Routing\\RouteActionHandler), Array)\n#14 \/var\/www\/nextcloud\/lib\/base.php(1010): OC\\Route\\Router->match('\/apps\/ocr')\n#15 \/var\/www\/nextcloud\/index.php(40): OC::handleRequest()\n#16 {main}","File":"\/var\/www\/nextcloud\/lib\/public\/AppFramework\/Db\/Mapper.php","Line":289}`

**Comment by janis91** [comment]
Could be the same behaviour as in: #56 Can you confirm?

**Comment by lordrascal** [comment]
hey, maybe, i have the directory added as an external source, altho on the same ubuntu system as nextcloud

**Comment by lordrascal** [comment]
ok, das war's. dürfte mit den Berechtigungen zusammenhängen, es hat funktioniert

**Comment by janis91** [comment]
Is there any log?

**Comment by lordrascal** [comment]
not that i'm aware of, just he ones when i try to do it in an external storage

**Comment by janis91** [comment]
The above mentioned ticket will be used for the discussion and more updates regarding this issue. Therefore I close this one.
