### ISSUE TITLE
OCR needs undocumented installation steps to work on newer systems (e. g. Debian Stretch)

### ISSUE THREAD

**Issue by stweil** [janis91/ocr#63]
An installation of the OCR app on Debian Stretch fails to work. Users are able to start the OCR with a selected language, but then see a never ending sequence of messages reporting that "Temp file does not exist.". This sequence can only be stopped by hacking the database and removing the row related to the OCR job. Technically, the code should reset the job status before raising the exception (see pull request #64).

The file which was not found exists in /tmp/ and has the correct permissions. Nevertheless, the PHP code claims that the file does not exist. This is caused by a security feature of systemd: apache2.service gets its own /tmp directory. Therefore /tmp seen by PHP code running in Apache2 is not the same as /tmp seen by the OCRWorker.php process.

It is possible to disable the security feature with a private /tmp for apache2.service, but that would be a bad solution. The better solution is using systemd to start OCRWorker.php and tell it to share /tmp with apache2.service. This works for me.

**Comment by stweil** [comment]
This systemd configuration file `/etc/systemd/system/nextcloud-ocr-worker.service` works with apache2.service:

    [Unit]
    Description=OCRWorker for Nextcloud OCR
    After=apache2.service
    JoinsNamespaceOf=apache2.service

    [Service]
    User=www-data
    Group=www-data
    ExecStart=/usr/bin/php /var/customers/webs/StefanWeil/weilnetz.de/cloud/apps/ocr/worker/OCRWorker.php
    Nice=19
    PrivateTmp=true
    Restart=always

    [Install]
    WantedBy=multi-user.target

It is based on the [code in the Wiki documentation](https://github.com/janis91/ocr/wiki/Configuration-and-Usage#usage-with-systemd), but adds `JoinsNamespaceOf=apache2.service` to join the `/tmp` directories seen by the interacting processes.

**Comment by janis91** [comment]
Thanks for your contribution. I will add this soon.

**Comment by janis91** [comment]
added to the respective part in the wiki and fixed the endless loop in #74. Thanks!
