### ISSUE TITLE
App "Array" cannot be installed.

### ISSUE THREAD

**Issue by gdgeorge** [janis91/ocr#67]
# Bug report
## Expected Behavior

Enabling the OCR app in Nextcloud 11 should succeed

## Current Behavior

`App "Array" cannot be installed because the following dependencies are not fulfilled: The command line tool ocrmypdf could not be found`

## Steps to Reproduce (for bugs)

1. Install Ocrmypdf-tess4 docker image 
2. Alias the ocrmypdf command using
`alias ocrmypdf='docker run --rm -v "$(pwd):/home/docker" ocrmypdf'`
3. Run `ocrmypdf ` on the CLI. (Success.)
4. Attempt to enable app in Nextcloud.

## Your Environment

* OCR version used: ocrmypdf-tess4:latest docker image
* Browser Name and version: Chrome latest
* Operating System and version (desktop or mobile): Dell PE2900 running Ubuntu 1604, Docker Server v. 17.01.3-ce 
* ownCloud/nextcloud version: (see ownCloud admin page or version.php) 11.02
* PHP version  7.0.17-2+deb.sury.org~xenial+1
* Database version 
* Are you using encryption: yes/no: no.

**Comment by janis91** [comment]
I don't know how Nextcloud checks that a dependency is installed or available on the system. Is the alias/command also available for the user that is used to run the NC server? Maybe therefore the user does not see it. Otherwise I would suggest the NC check for the dependency is not the best. Can you try to use the ocrmypdf command with the NC user?

**Comment by gdgeorge** [comment]
Bingo. 
` sudo -u www-data ocrmypdf` 
yields 
`sudo: ocrmypdf: command not found`
yet the alias runs from other accounts without problems.  I've tried creating a file, `www-data`,  in `/ect/sudoers.d` but I'm getting errors for anything related to the aliased command.  I've tried putting the whole unaliased command in that file as well.  It's either my syntax or sudoers doesn't like the user www-data.  Any ideas?

**Comment by janis91** [comment]
Actually I would try to:
Add the docker user group, if it doesn't already exist:
`sudo groupadd docker`
Add the www-data or other server user to the group:
`sudo gpasswd -a www-data docker`
restart the server and try to create the alias once again with the www-data user.
or: go for a bash script which executes the docker run command and make it available and executable for the www-data user in the respective bin folder.

But this is without warranty. I don't know what's the suggested and especially **safe** way in this case. Always make sure to be on the safe side when you grant access to system resources and commands over a web server.

**Comment by gdgeorge** [comment]
Well I played with it some more and I can make the command run except for the www-data user.  Even with a script owned root:www-data and 75x permissions, it's not cooperating.  The latest iteration involves an alias loaded from /etc/profile, that calls the script. I'd think that with the appropriate permissions, su www-data ocrmypdf would work but no such luck yet.  I'll double check my groups again tomorrow and if still no dice, I'll get back to it in a day or so.  Thanks for your help.

**Comment by janis91** [comment]
Would be nice if you could write a solution in the case you find one. For now I will close this issue. Sorry that I cannot provide any further help...
