### ISSUE TITLE
[Feature Request] Folder processing

### ISSUE THREAD

**Issue by janis91** [janis91/ocr#80]
Mark a folder and process it. Maybe even specify a folder in the user settings, which then can be processed automatically by the cron jobs in nextcloud.

**Comment by seimsel** [comment]
Hey
Thanks alot for this awesome plugin! :+1:

A feature where all new uploads of a specific filetype in a specific folder are automatically processed would be very practical. Also it should be possible to enter the destination directory.

Keep up the good work!

Cheers,
Simon

**Comment by Braintelligence** [comment]
This would be a killer feature.

**Comment by mathiasconradt** [comment]
+1 Totally agree. 

> Maybe even specify a folder in the user settings, which then can be processed automatically by the cron jobs in nextcloud.

I think more than one folder should be possible to be marked. How about applying a certain tag to a folder which would then automatically OCR-process new documents in it?

For example, if a folder has a tag `ocr-auto` or `ocr-auto-pdf` or `ocr-auto-txt`, whenever a new documents is added to the folder, it gets processed. This approach is maybe more flexible and causes less implementation work to be done on the OCR settings page.

**Comment by janis91** [comment]
@mathiasconradt I like the idea and I tried to create a Cron job task that is calling a service that should initialize the process foreach folder with that tag. Unfortunately, I don't understand how to add/register a cron job and how to get a service method running from that BackgroundJob\Job class. I tried so much and didn't even get a simple log message from it.

Please don't take offense of the next paragraph, just some thaughts and feelings that I want to share with you when it comes to app development for NC (maybe other devs or people that only considered developing apps for NC but struggled to much in the beginning have the same feelings, maybe not):
The dev docs are really not a good point for help when it comes to app development. In most cases the approach that is proposed there is deprecated since versions. The main problem I have is that I do the app development really in my rare and worthy spare time - like today (sunday). PHP is not the language I personally love (normally I develop in Java or JavaScript) and therefore is always a bit of struggle when it comes to some more complex things, for example to understand the framework and especially determine if I should implement something by my own or if something is already provided by the framework. Essentially I miss a "real world" example app that is doing things like it should be done with up-to-date framework usage. 
I personally don't have the time or let's say it like this: I do not want to invest hours and hours to determine how properly set up some background job - for example - by searching the source code of different nextcloud apps. It's really frustrating and blocks especially the feature development of this app in most cases.
There is no lack of support in the forums or on github, but for me it is a really big thing if you can just look at a good example app or more up to date and complete documentation. Compared to asking a question in the forums or on github and maybe don't get a complete answer... asking again... and again. It consumes so much time that I often don't even want to start developing on certain features, because I know I would probably have to spend hours just for investigating how a current approach that is not deprecated looks like.

I hope I pointed out some things that might be considered a bit more. I personally like Nextcloud, the idea of open source, the community and the product as a result itself. And I just want to give my opinion on what could be improved to drive it forward. And enabling other people building their own apps is one key to success in my opinion.

For today I will stop trying to figure out how this can be done.. Maybe I will give it another try in a week or so..
