### ISSUE TITLE
Automate compilation of js artifacts

### ISSUE THREAD

**Issue by janis91** [janis91/ocr#88]
As long as this bug: https://github.com/webpack/webpack/issues/4824
is not fixed, I keep the overwriting of underscore and other dependencies by hand. Maybe this will be fixed in a few months. Then I can change this behaviour.

**Comment by janis91** [comment]
- [ ] remove after-build.sh
- [ ] edit travis to build-prod behaviour

**Comment by janis91** [comment]
first step is taken, but after-build.sh cannot be removed yet. A upgrade to version3 of webpack is necessary first.

**Comment by janis91** [comment]
@MorrisJobke I already wrote you an email regarding this:
Es geht um transifex translations.
> Hallo Morris,
> du hattest mir vor einem Jahr ungefähr die transifex translations für mein OCR Projekt aufgesetzt. Seit dem ist in meinem Projekt einiges passiert und ich habe beschlossen meine javascript addons mithilfe von TypeScript zu schreiben und mit webpack auszuliefern. Jetzt ist es so, dass ich ungern die fertigen bundles mit in die sourcen legen würde und auf github pushen, sondern eigentlich würde ich gerne die Extraktion auf den TypeScript sourcen laufen lassen und die javascript files nur im fertig gepackten Release package ausliefern, dann aber eben mit den dazugehörigen translation-files. 

> Ich vermute mal, dass ich dafür selbst etwas am extraktions script / cronjob anpassen müsste bzw. ein individuell auf mein repo angepasster Job laufen müsste und kann mir vorstellen, dass das relativ umständlich sein könnte. Daher die Frage: Ist das möglich? Und wenn ja, was muss ich dafür tun?

> Notfalls kann ich auch den webpack output wieder einchecken, es ist nur eben etwas unschön vor jedem git push den build lokal anstoßen zu müssen, damit die aktuellen bundle files da sind.

**Comment by MorrisJobke** [comment]
I read it, sorry for not answering it yet, because I was just busy with other stuff. Sure we can do that - the problem is just that it maybe cause problems every time the dependencies are updated, but we can give it a try. How to build it?

**Comment by janis91** [comment]
@MorrisJobke What do you mean exactly with 

> maybe cause problems every time the dependencies are updated

What do you want to build exactly?

I saw that you updated the included files for typescript. That's nice. Is it so that I need to use t and n as global functions in my files exactly like in the javascript before? Then I can try to adjust this :-)

**Comment by MorrisJobke** [comment]
> I saw that you updated the included files for typescript. That's nice. Is it so that I need to use t and n as global functions in my files exactly like in the javascript before? Then I can try to adjust this :-)

Basically yes - it just also searches those methods.



> What do you want to build exactly?

The more tools it depends on during build time the more often it could break appart, but having a single `make` doing all of the dependency fetching, then I could integrate it for this app and extract the data from the compiled assets.

**Comment by janis91** [comment]
@MorrisJobke I think I don't undertand what you mean. If you look into that file for example:
https://github.com/janis91/ocr/blob/master/js/src/app/view/view.ts#L37
now t and n are used like in javascript. Is there any issue with that or will it work to extract the translation strings now?

**Comment by MorrisJobke** [comment]
Let me check why it seems to not include it.

**Comment by MorrisJobke** [comment]
> Let me check why it seems to not include it.

Works all fine (was only not yet translated):

```
#: /Users/morris/Projects/nextcloud/server/apps2/ocr/js/src/app/view/view.ts:46
msgid "Process"
msgstr ""

#: /Users/morris/Projects/nextcloud/server/apps2/ocr/js/src/app/view/view.ts:46
msgid "Replace"
msgstr ""
```

**Comment by janis91** [comment]
@MorrisJobke yeah I saw it. The only strings that did not get extracted yet are:

https://github.com/janis91/ocr/blob/2ec62b408163c55ac9de794240be32fa96c7176c/js/src/app/view/view.ts#L68
and
https://github.com/janis91/ocr/blob/2ec62b408163c55ac9de794240be32fa96c7176c/js/src/app/view/view.ts#L71

Is this because of the templated string, because the next line was extracted?
https://github.com/janis91/ocr/blob/2ec62b408163c55ac9de794240be32fa96c7176c/js/src/app/controller/controller.ts#L164

**Comment by janis91** [comment]
Should i change this by just assign it to a variable first or is this an issue of the extraction logic?

**Comment by MorrisJobke** [comment]
Weird ... always the plural stuff. I will have a look at this tomorrow.

**Comment by MorrisJobke** [comment]
All of the linked strings are extracted properly now. Are there any other issues?

**Comment by janis91** [comment]
It seems like everything is working fine now. 👍 
I will close this then. Thanks!
