### ISSUE TITLE
l10n : Improvement from transifex

### ISSUE THREAD

**Issue by rakekniven** [janis91/ocr#89]
File:  ocr/js/ocrview.js

line 16 : t('ocr', 'No languages for tesseract available')+""

Idea:
How about following up with "Install the Tesseract language pack (plugin?) for your local language to ORC your files." as this is quite a complex issue.
If you already knew, you wouldn't be making the mistake, and if you did, you wont understand the error message.

For discussion see https://www.transifex.com/nextcloud/nextcloud/translate/#de_DE/$/98255861?issue=yes

**Comment by janis91** [comment]
As I am currently changing the underlaying architecture a bit (the worker will become a Docker image and Redis will be used for job queuing) this is a valid proposal for the version now, but in the future the languages will be configured in the administration section.
See: #68 
Thanks anyway!
