### ISSUE TITLE
OCR in shared (public) NC

### ISSUE THREAD

**Issue by stweil** [janis91/ocr#96]
The new Nextcloud 12 deactivates the OCR app and reports that it is incompatible.

**Comment by stweil** [comment]
The pre-release v3.0.0-beta.1 added support for Nextcloud 12 and seems to work basically.

Nextcloud greatly improved shared files and folders: it is now possible to share a link to a document so that the linked document can be edited with Collabora Online.

A similar feature would be useful for OCR, too. I'd like to share a directory (or a whole directory tree) with images, and it should be possible for everybody who has a shared link with write access to run OCR.

**Comment by janis91** [comment]
This sounds good. I will put it in the backlog ;-)

**Comment by janis91** [comment]
NC 12 will be supported from v3 on. It is now in a really good shape, I will publish it soon.

**Comment by stweil** [comment]
I just updated to latest version and was surprised that it now requires a Docker container. Is it possible to go back to a version without that requirement? I'd like to avoid Docker on the server.
